Add alias for onepub

diff --git a/home/exact_dot_dotfiles/shellrc.tmpl b/home/exact_dot_dotfiles/shellrc.tmpl
--- a/home/exact_dot_dotfiles/shellrc.tmpl
+++ b/home/exact_dot_dotfiles/shellrc.tmpl
@@ -130,9 +130,6 @@ fi
 
 # General aliases
 
-alias c='cd'
-alias cat='bat'
-
 function dart() {
   if [[ ! -f "$PWD/.fvm/fvm_config.json" ]]; then
     command dart "$@" || return $?
@@ -141,8 +138,6 @@ function dart() {
     fvm dart "$@"
   fi
 }
-
-alias e='nvim'
 
 function flutter() {
   if [[ ! -f "$PWD/.fvm/fvm_config.json" ]]; then
@@ -153,6 +148,18 @@ function flutter() {
   fi
 }
 
+function onepub() {
+  if [[ ! -f "$PWD/.fvm/fvm_config.json" ]]; then
+    command onepub "$@" || return $?
+    echo -e "\n\e[33m\e[1mWARN:\e[0m\e[33m FVM configuration not found. Did you forget to run \`fvm use <version>\`?\e[0m"
+  else
+    fvm onepub "$@"
+  fi
+}
+
+alias c='cd'
+alias cat='bat'
+alias e='nvim'
 alias g='git'
 alias l='ls'
 alias vim='nvim'
